//
//  NewMessageRouter.swift
//  ChatMSG
//
//  Created by Julia on 2023/04/26.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewMessageRoutingLogic {
    func receiverRouteToSender(_ receiver: String)
    func senderRouteToDatePick(_ sender: String)
    func datePickRouteToMessageType(_ date: Date)
    func messageTypeRouteToSituation(type: String, writingStyle: String)
}

protocol NewMessageDataPassing {
    var dataStore: NewMessageDataStore? { get }
}

final class NewMessageRouter: NewMessageRoutingLogic, NewMessageDataPassing {
    
    weak var recevierVC: ReceiverViewController?
    weak var senderVC: SenderViewController?
    weak var datePickVC: DatePickViewController?
    weak var typeVC: MessageTypeViewController?
    weak var situationVC: SituationViewController?
    
    var dataStore: NewMessageDataStore?
  
    func receiverRouteToSender(_ receiver: String) {
        let senderVC = SenderViewController()
        recevierVC?.navigationController?.pushViewController(senderVC, animated: true)
        dataStore?.receiver = receiver
    }
    
    func senderRouteToDatePick(_ sender: String) {
        let datePickVC = DatePickViewController()
        senderVC?.navigationController?.pushViewController(datePickVC, animated: true)
        dataStore?.sender = sender
    }
    
    func datePickRouteToMessageType(_ date: Date) {
        let typeVC = MessageTypeViewController()
        datePickVC?.navigationController?.pushViewController(typeVC, animated: true)
        dataStore?.date = date
    }
    
    func messageTypeRouteToSituation(type: String, writingStyle: String) {
        let situationVC = SituationViewController()
        typeVC?.navigationController?.pushViewController(situationVC, animated: true)
        dataStore?.type = type
        dataStore?.writingStyle = writingStyle
    }
    
//    func senderRouteToDatePicker() {
//
//    }
    
//    func routeToSomewhere() {
//        let destinationVC = UIViewController()
//        guard var destinationDS = destinationVC.router?.dataStore else { return }
//        guard let dataStore = dataStore else { return }
//        guard let viewController = viewController else { return }
//        passDataToSomewhere(source: dataStore, destination: &destinationDS)
//        navigateToSomewhere(source: viewController, destination: destinationVC)
//    }

  // MARK: - Navigation
  

  
  // MARK: - Passing data
  
}
