//
//  NewMessageModels.swift
//  ChatMSG
//
//  Created by Julia on 2023/04/26.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MakeMessage {
    // MARK: -  Use Cases
      enum makeNewMessage {
          
        struct Request {
            var receiver: String
            ///송신자
            var sender: String
            ///메세지에 담길 날짜
            var date: Date
            ///메세지 유형
            var type: String
            ///어체
            var writingStyle: String
            ///자세한 상황 설명
            var situation: String
            
        }

        struct Response {
            var newMessage: String
            
            struct Error {
                var message: String
            }
        }
          
        struct ViewModel {
            
            var displayedMessage: String
            
            struct Error {
                var message: String
            }
        }
    }
}
