//
//  NewMessageWorker.swift
//  ChatMSG
//
//  Created by Julia on 2023/04/26.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewMessageWorkerProtocol {
    func requestNewMessage(_ message: NewMessage.makeNewMessage.Request) async throws -> String
}

final class NewMessageWorker: NewMessageWorkerProtocol {
    private var datasource: OpenAIDataSourceProtocol
    
    init(datasource: OpenAIDataSourceProtocol = OpenAIDataSource()) {
        self.datasource = datasource
    }
    
    func requestNewMessage(_ request: NewMessage.makeNewMessage.Request) async throws -> String {
        let output = translate(request)
        let result = try await datasource.getMessage(request: output)
        print("result", result)
        return result
    }
        
    func translate(_ model: NewMessage.makeNewMessage.Request) -> OpenAIRequest {
        return OpenAIRequest(type: model.type,
                             receiver: model.receiver,
                             sender: model.sender,
                             date: stringToDate(model.date),
                             stylistic: model.stylistic,
                             location: model.location ?? "없음",
                             length: "\(model.length)자",
                             situation: model.situation)
    }
    
    private func stringToDate(_ data: Date) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy년 MM월 dd일"
        return dateFormatter.string(from: data)
    }
}
