//
//  NewMessagePresenter.swift
//  ChatMSG
//
//  Created by Julia on 2023/04/26.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewMessagePresentationLogic {
    func presentNewMessage(response: NewMessage.makeNewMessage.Response)
}

final class NewMessagePresenter: NewMessagePresentationLogic {
    weak var viewController: NewMessageDisplayLogic?
  
    // MARK: -  Do something
    
    func presentNewMessage(response: NewMessage.makeNewMessage.Response) {
        let viewModel = NewMessage.makeNewMessage.ViewModel(displayedMessage: response.newMessage)
        Task { @MainActor in
            viewController?.displaySomething(viewModel: viewModel)
        }
    }
}
