//
//  NewMessageViewController.swift
//  ChatMSG
//
//  Created by Julia on 2023/04/26.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Then

@MainActor
protocol NewMessageDisplayLogic: AnyObject {
    func displaySomething(viewModel: NewMessage.makeNewMessage.ViewModel)
}

final class NewMessageViewController: UIViewController, NewMessageDisplayLogic {
    var interactor: NewMessageBusinessLogic?
    var router: (NewMessageRoutingLogic & NewMessageDataPassing)?
    
    // MARK: - Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        self.setup()
    }
    
    // MARK: - Setup
    
    private func setup() {
        let viewController = self
        let interactor = NewMessageInteractor()
        let presenter = NewMessagePresenter()
        let router = NewMessageRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: -  UIComponent
    private lazy var typeTextField: UnderLineView = UnderLineView().then {
        $0.configure(title: "어떤 종류의 메세지인가요?")
//        self.view.backgroundColor = .blue
    }
    
    private lazy var datePickerView: WheelPickerView = WheelPickerView().then {
        $0.configure(type: .number,
                     title: "메세지의 상황 속 날짜는 언제인가요?")
//        self.view.backgroundColor = .yellow
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.view.backgroundColor = .systemBackground
        self.setUpLayout()
        doSomething()
        //test
    }
    
    private func setUpLayout() {
        [self.typeTextField, self.datePickerView].forEach {
            self.view.addSubview($0)
        }
        
        self.typeTextField.snp.makeConstraints { make in
            make.top.equalTo(self.view.safeAreaLayoutGuide.snp.top)
            make.leading.trailing.equalToSuperview().inset(20)
            make.height.equalTo(80)
        }
        
        self.datePickerView.snp.makeConstraints { make in
            make.top.equalTo(self.typeTextField.snp.bottom).offset(20)
            make.leading.trailing.equalToSuperview().inset(20)
            make.height.equalTo(90)
        }
    }
    
    // VIP Cycle Start
    func doSomething() {
        let request = NewMessage.makeNewMessage.Request(type: "성적 문의",
                                                        receiver: "000교수님",
                                                        sender: "IT융합자율학부 000",
                                                        date: Date.now,
                                                        stylistic: "존댓말",
                                                        location: nil,
                                                        length: 400,
                                                        situation: "자료구조 시험을 봤는데 기대했던 성적만큼 받지 못했어. 성적을 문의하고 싶어.")
//        interactor?.makeNewMessage(request: request)
    }
    
    // MARK: - Display Logic
  
    func displaySomething(viewModel: NewMessage.makeNewMessage.ViewModel) {
        //nameTextField.text = viewModel.name
        print(viewModel)
    }
    
}
