//
//  MessageListPresenter.swift
//  ChatMSG
//
//  Created by Julia on 2023/04/26.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MessageListPresentationLogic {
    func presentMessageList(response: MessageList.Something.Response)
}

final class MessageListPresenter: MessageListPresentationLogic {
    weak var viewController: MessageListDisplayLogic?
  
    func presentMessageList(response: MessageList.Something.Response) {
        let displayedMessageList: [MessageList.Something.ViewModel.DisplayedMessage] = response.messageList.map {
            return MessageList.Something.ViewModel.DisplayedMessage(imoji: $0.imoji,
                                                                    typeAndReceiver: "[\($0.type)] \($0.receiver)",
                                                                    createdDate: $0.createdDate.slashFormat())
        }
        let viewModel = MessageList.Something.ViewModel(displayedMessageList: displayedMessageList)
        Task { @MainActor in
            viewController?.displaySomething(viewModel: viewModel)
        }
    }

}
