//
//  MessageListInteractor.swift
//  ChatMSG
//
//  Created by Julia on 2023/04/26.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MessageListBusinessLogic {
    func doSomething(request: MessageList.Something.Request)
}

protocol MessageListDataStore {
    //var name: String { get set }
}

final class MessageListInteractor: MessageListBusinessLogic, MessageListDataStore {
    var presenter: MessageListPresentationLogic?
    private var worker: MessageListWorker?
    //var name: String = ""
  
    // MARK: - do Something
  
    func doSomething(request: MessageList.Something.Request) {
        worker = MessageListWorker()
//        worker?.doSomeWork()
    
        let response = MessageList.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
