//
//  MessageListViewController.swift
//  ChatMSG
//
//  Created by Julia on 2023/04/26.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit
import OpenAISwift

struct Dummy {
    let type: String
    let date: String
    let receiver: String
}

@MainActor
protocol MessageListDisplayLogic: AnyObject {
    func displaySomething(viewModel: MessageList.Something.ViewModel)
}

final class MessageListViewController: UIViewController, MessageListDisplayLogic {
    var interactor: MessageListBusinessLogic?
    var router: (MessageListRoutingLogic & MessageListDataPassing)?
    
    // MARK: - Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        self.setup()
    }
    
    // MARK: - Setup
    
    private func setup() {
        let viewController = self
        let interactor = MessageListInteractor()
        let presenter = MessageListPresenter()
        let router = MessageListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.listVC = viewController
        router.dataStore = interactor
    }
    
    // MARK: -  UIComponent
    private lazy var messageListTableView: UITableView = {
        let view = UITableView()
        view.backgroundColor = .systemBackground
        view.rowHeight = 100
        view.dataSource = self
        view.delegate = self
        view.register(MessageListCell.self)
        return view
    }()
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.setUpLayout()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        self.setUpNavigationBar()
        self.fetchMessageList()
    }
    
    private func setUpNavigationBar() {
        self.navigationItem.title = "최근 만든 메세지"
        let item = UIBarButtonItem(image: UIImage(systemName: "square.and.pencil"),
                                   style: .plain,
                                   target: self,
                                   action: #selector(didTapNewMessageButton)) // TODO: 작성 페이지 연결하기
        self.navigationItem.rightBarButtonItem = item
    }
    
    @objc func didTapNewMessageButton() {
        if let router = router {
            router.routeToNewMessage()
        }
    }
    
    private func setUpLayout() {
        [self.messageListTableView].forEach { view in
            self.view.addSubview(view)
        }
        
        self.messageListTableView.snp.makeConstraints { make in
            make.top.equalTo(self.view.safeAreaLayoutGuide.snp.top)
            make.leading.trailing.bottom.equalToSuperview().inset(10)
        }
    }
    
    // VIP Cycle Start
    func fetchMessageList() {
        self.messageListTableView.reloadData()
        self.interactor?.fetchMessageList()
    }
    
    // MARK: - Display Logic
    var displayedMessageList: [MessageList.Something.ViewModel.DisplayedMessage] = [] {
        didSet {
            self.messageListTableView.reloadData()
        }
    }
    
    func displaySomething(viewModel: MessageList.Something.ViewModel) {
        self.displayedMessageList = viewModel.displayedMessageList
    }
    
}

extension MessageListViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.displayedMessageList.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(type: MessageListCell.self, for: indexPath)
        cell.configure(data: self.displayedMessageList[indexPath.row])
        return cell
    }
}

extension MessageListViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if let router = router {
            router.routeToMessageDetail(index: indexPath.row)
        }
    }
    
    func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath) {
        if editingStyle == .delete {
            interactor?.deleteMessage(indexPath.row)
            self.displayedMessageList.remove(at: indexPath.row)
            self.messageListTableView.reloadData()
        }
    }
}
