//
//  MessageListWorker.swift
//  ChatMSG
//
//  Created by Julia on 2023/04/26.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MessageListWorkerProtocol {
    func fetchMessageList() async -> [MessageItem]
    func removeMessage(_ data: MessageItem) async
}

final class MessageListWorker: MessageListWorkerProtocol {
    
    func fetchMessageList() async -> [MessageItem] {
        let messages: [MessageItem] = await Message.fetchAllMessage()
        return messages
    }

    func removeMessage(_ data: MessageItem) async {
        await Message.deleteMessage(message: data)
    }
    
}
