//
//  MessageListViewController.swift
//  ChatMSG
//
//  Created by Julia on 2023/04/26.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit

@MainActor
protocol MessageListDisplayLogic: AnyObject {
    func displaySomething(viewModel: MessageList.Something.ViewModel)
}

final class MessageListViewController: UIViewController, MessageListDisplayLogic {
    var interactor: MessageListBusinessLogic?
    var router: (MessageListRoutingLogic & MessageListDataPassing)?
    
    // MARK: - Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        self.setup()
    }
    
    // MARK: - Setup
    
    private func setup() {
        let viewController = self
        let interactor = MessageListInteractor()
        let presenter = MessageListPresenter()
        let router = MessageListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: -  UIComponent
    private lazy var messageListTableView: UITableView = {
        let view = UITableView()
        view.backgroundColor = .systemBackground
        return view
    }()
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.setUpLayout()
        self.setUpNavigationBar()
        doSomething()
    }
    
    private func setUpNavigationBar() {
        self.navigationItem.title = "최근 만든 메세지"
        let item = UIBarButtonItem(image: UIImage(systemName: "square.and.pencil"),
                                   style: .plain,
                                   target: self,
                                   action: nil) // TODO: 작성 페이지 연결하기
        self.navigationItem.rightBarButtonItem = item
    }
    
    private func setUpLayout() {
        [self.messageListTableView].forEach { view in
            self.view.addSubview(view)
        }
        
        self.messageListTableView.snp.makeConstraints { make in
            make.top.equalTo(self.view.safeAreaLayoutGuide.snp.top)
            make.leading.bottom.trailing.equalToSuperview()
        }
    }
    
    // VIP Cycle Start
    func doSomething() {
        let request = MessageList.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    // MARK: - Display Logic
  
    func displaySomething(viewModel: MessageList.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
    
}

