//
//  MessageListPresenter.swift
//  ChatMSG
//
//  Created by Julia on 2023/04/26.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MessageListPresentationLogic {
    func presentSomething(response: MessageList.Something.Response)
}

final class MessageListPresenter: MessageListPresentationLogic {
    weak var viewController: MessageListDisplayLogic?
  
    // MARK: -  Do something
    
    func presentSomething(response: MessageList.Something.Response) {
        
        let viewModel = MessageList.Something.ViewModel()
        Task { @MainActor in
            viewController?.displaySomething(viewModel: viewModel)
        }
    }
}
