//
//  MessageListRouter.swift
//  ChatMSG
//
//  Created by Julia on 2023/04/26.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MessageListRoutingLogic {
    func routeToMessageDetail(index: Int)
}

protocol MessageListDataPassing {
    var dataStore: MessageListDataStore? { get }
}

final class MessageListRouter: MessageListRoutingLogic, MessageListDataPassing {
    weak var viewController: MessageListViewController?
    var dataStore: MessageListDataStore?
  

    // MARK: -  Routing
    
    func routeToMessageDetail(index: Int) {
        let destinationVC = MessageDetailViewController()
        guard let dataStore = dataStore,
              var detailDataStore = destinationVC.router?.dataStore,
              let vc = viewController else {
            return
        }
        vc.navigationController?.pushViewController(destinationVC, animated: true)
        detailDataStore.message = dataStore.messageList[index]
    }

  
}
