//
//  MessageListModels.swift
//  ChatMSG
//
//  Created by Julia on 2023/04/26.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MessageList {
    // MARK: -  Use Cases
      enum Something {
          
        struct Request {
            
        }

        struct Response {
            var messageList: [MessageItem]
        }
          
        struct ViewModel {
            struct DisplayedMessage {
                var imoji: String
                var typeAndReceiver: String
                var createdDate: String
            }
            
            var displayedMessageList: [DisplayedMessage]
        }
    }
}
