//
//  MessageDetailRouter.swift
//  ChatMSG
//
//  Created by Julia on 2023/05/04.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MessageDetailRoutingLogic {
}

protocol MessageDetailDataPassing {
    var dataStore: MessageDetailDataStore? { get }
}

final class MessageDetailRouter: MessageDetailRoutingLogic, MessageDetailDataPassing {
    weak var viewController: MessageDetailViewController?
    var dataStore: MessageDetailDataStore?
  
}
