//
//  MessageDetailPresenter.swift
//  ChatMSG
//
//  Created by Julia on 2023/05/04.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MessageDetailPresentationLogic {
    func presentSomething(response: MessageDetail.Something.Response)
}

final class MessageDetailPresenter: MessageDetailPresentationLogic {
    weak var viewController: MessageDetailDisplayLogic?
  
    // MARK: -  Do something
    
    func presentSomething(response: MessageDetail.Something.Response) {
        
        let viewModel = MessageDetail.Something.ViewModel()
        Task { @MainActor in
            viewController?.displaySomething(viewModel: viewModel)
        }
    }
}
