//
//  MessageDetailPresenter.swift
//  ChatMSG
//
//  Created by Julia on 2023/05/04.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MessageDetailPresentationLogic {
    func presentSomething(response: MessageDetail.Something.Response)
}

final class MessageDetailPresenter: MessageDetailPresentationLogic {
    weak var viewController: MessageDetailDisplayLogic?
      
    func presentSomething(response: MessageDetail.Something.Response) {
        let message = response.message
        let title: String = "\(message.receiver)에게 📮"
        let description: String = "\(message.sender)로서 보낸 \(message.type) 메세지 \n\(message.createdDate.hangleFormat())에 보냈어요!"
        let displayedMessage = MessageDetail.Something.ViewModel.displayedMessage(title: title,
                                                                                  description: description,
                                                                                  result: message.result)
        let viewModel = MessageDetail.Something.ViewModel(displayedMessage: displayedMessage)
        Task { @MainActor in
            viewController?.displaySomething(viewModel: viewModel)
        }
    }
}
