//
//  MessageDetailModels.swift
//  ChatMSG
//
//  Created by Julia on 2023/05/04.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MessageDetail {
    // MARK: -  Use Cases
      enum Something {
          
        struct Request {
            
        }

        struct Response {
            var message: MessageItem
            
            struct Error {
                var message: String
            }
        }
          
        struct ViewModel {
            struct displayedMessage {
                var title: String
                var description: String
                var result: String
            }
            
            struct Error {
                var message: String
            }
            var displayedMessage: displayedMessage
        }
    }
}
